---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker-api
  namespace: api
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      $setElementOrder/containers:
      - name: api
      $setElementOrder/initContainers:
      - name: database-migration
      containers:
      - image: gcr.io/track-compliance/api:master-8b9ad74
        name: api
      initContainers:
      - image: gcr.io/track-compliance/api:master-8b9ad74
        name: database-migration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker-frontend
  namespace: frontend
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      $setElementOrder/containers:
      - name: frontend
      containers:
      - image: gcr.io/track-compliance/frontend
        name: frontend
