---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker-api
  namespace: api
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.api: regexp:^(master-*)$
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      $setElementOrder/containers:
      - name: api
      $setElementOrder/initContainers:
      - name: database-migration
      containers:
      - image: gcr.io/track-compliance/api:master-8b9ad74
        name: api
      initContainers:
      - image: gcr.io/track-compliance/api:master-3cf29a1
        name: database-migration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker-frontend
  namespace: frontend
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.frontend: regexp:^(master-*)$
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      $setElementOrder/containers:
      - name: frontend
      containers:
      - image: gcr.io/track-compliance/frontend:master-a1961df
        name: frontend
