apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../bases
- ingressgateway.yaml
images:
- name: gcr.io/track-compliance/api
  newTag: master-75fe6f3
- name: gcr.io/track-compliance/frontend
  newTag: master-a3ca9c3
patchesStrategicMerge:
- tracker-api-deployment.yaml
- tracker-frontend-deployment.yaml
