apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../bases
- ingressgateway.yaml
images:
- name: gcr.io/track-compliance/api
  newTag: master-5866888
- name: gcr.io/track-compliance/frontend
  newTag: master-6e7e449
secretGenerator:
- envs:
  - postgres.env
  name: postgres
  namespace: api
- envs:
  - api.env
  name: api
  namespace: api
patchesStrategicMerge:
- tracker-api-deployment.yaml
- tracker-frontend-deployment.yaml
