apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../bases
- ingressgateway.yaml
images:
- name: gcr.io/track-compliance/api
  newTag: master-71ec20f
- name: gcr.io/track-compliance/frontend
  newTag: master-c5a19fd
secretGenerator:
- envs:
  - postgres.env
  name: postgres
  namespace: api
- envs:
  - api.env
  name: api
  namespace: api
patchesStrategicMerge:
- tracker-api-deployment.yaml
- tracker-frontend-deployment.yaml
