apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../bases
- ingressgateway.yaml
images:
- name: gcr.io/track-compliance/api
  newTag: master-d97b01d
- name: gcr.io/track-compliance/frontend
  newTag: master-e821237
patchesStrategicMerge:
- tracker-api-deployment.yaml
- tracker-frontend-deployment.yaml
