kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: api-network-policy
  namespace: api
spec:
  podSelector:
    matchLabels:
      role: backend
      purpose: api
  ingress:
    # Ingress policy for db communications
    - from:
      - podSelector:
          matchLabels:
            role: backend
            purpose: db
      ports:
        - port: 8529
    # Ingress policy for istio ingress gateway
    - from:
      - podSelector:
          matchLabels:
            app: istio-ingressgateway
      ports:
        - port: 4000
    # Allow external communications (this pretty much makes the other policies obsolete)
    - ports:
      - port: 53
      - port: 80
      - port: 443
  policyTypes:
    - Egress
  egress:
      - ports:
        # Allow DNS resolution
        - port: 53
        # Allow external communication
        - port: 80
        - port: 443
      - to:
        - podSelector:
            matchLabels:
              role: backend
              purpose: db
        ports:
          - port: 8529
      - to:
        - podSelector:
            matchLabels:
              app: istio-ingressgateway
        ports:
          - port: 4000
