kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: db-network-policy
  namespace: db
spec:
  podSelector: {}
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            purpose: backend
      ports:
        - port: 8529
          protocol: TCP
